name: Auto Telegram Parser

on:
  schedule:
    # Автозапуск каждые 30 минут (24/7)
    - cron: '*/30 * * * *'
  workflow_dispatch: # Кнопка ручного запуска на сайте

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install telethon

    - name: Run Parser Script
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        MY_CHAT_ID: ${{ secrets.MY_CHAT_ID }}
      # Сначала заходим в папку new, а потом запускаем парсер!
      run: |
        cd new
        python test_tg_parser.py
